<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Genre extends \App\Entity\Genre implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'children' => [parent::class, 'children', null],
        "\0".parent::class."\0".'color' => [parent::class, 'color', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'parent' => [parent::class, 'parent', null],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null],
        "\0".parent::class."\0".'songs' => [parent::class, 'songs', null],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null],
        "\0".parent::class."\0".'tracks' => [parent::class, 'tracks', null],
        "\0".parent::class."\0".'year' => [parent::class, 'year', null],
        'children' => [parent::class, 'children', null],
        'color' => [parent::class, 'color', null],
        'description' => [parent::class, 'description', null],
        'id' => [parent::class, 'id', null],
        'parent' => [parent::class, 'parent', null],
        'slug' => [parent::class, 'slug', null],
        'songs' => [parent::class, 'songs', null],
        'title' => [parent::class, 'title', null],
        'tracks' => [parent::class, 'tracks', null],
        'year' => [parent::class, 'year', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
