<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Album extends \App\Entity\Album implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'artists' => [parent::class, 'artists', null],
        "\0".parent::class."\0".'genres' => [parent::class, 'genres', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'label' => [parent::class, 'label', null],
        "\0".parent::class."\0".'liked' => [parent::class, 'liked', null],
        "\0".parent::class."\0".'relase_date_precision' => [parent::class, 'relase_date_precision', null],
        "\0".parent::class."\0".'release_date' => [parent::class, 'release_date', null],
        "\0".parent::class."\0".'slug' => [parent::class, 'slug', null],
        "\0".parent::class."\0".'spotify_id' => [parent::class, 'spotify_id', null],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null],
        "\0".parent::class."\0".'tracks' => [parent::class, 'tracks', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        'artists' => [parent::class, 'artists', null],
        'genres' => [parent::class, 'genres', null],
        'id' => [parent::class, 'id', null],
        'label' => [parent::class, 'label', null],
        'liked' => [parent::class, 'liked', null],
        'relase_date_precision' => [parent::class, 'relase_date_precision', null],
        'release_date' => [parent::class, 'release_date', null],
        'slug' => [parent::class, 'slug', null],
        'spotify_id' => [parent::class, 'spotify_id', null],
        'title' => [parent::class, 'title', null],
        'tracks' => [parent::class, 'tracks', null],
        'type' => [parent::class, 'type', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
