<?php

namespace ContainerHOf4bZ6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UhUKKZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Uh_UKKZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Uh_UKKZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'genreRepository' => ['privates', 'App\\Repository\\GenreRepository', 'getGenreRepositoryService', true],
            'repository' => ['privates', 'App\\Repository\\TrackRepository', 'getTrackRepositoryService', true],
        ], [
            'genreRepository' => 'App\\Repository\\GenreRepository',
            'repository' => 'App\\Repository\\TrackRepository',
        ]);
    }
}
