<?php

namespace ContainerHOf4bZ6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArtistAutocompleteFieldService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AutocompleteField\ArtistAutocompleteField' shared autowired service.
     *
     * @return \App\Form\AutocompleteField\ArtistAutocompleteField
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AutocompleteField/ArtistAutocompleteField.php';

        return $container->privates['App\\Form\\AutocompleteField\\ArtistAutocompleteField'] = new \App\Form\AutocompleteField\ArtistAutocompleteField();
    }
}
