<?php

namespace ContainerHOf4bZ6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackController4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Web\TrackController' shared autowired service.
     *
     * @return \App\Controller\Web\TrackController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Web/TrackController.php';

        $container->services['App\\Controller\\Web\\TrackController'] = $instance = new \App\Controller\Web\TrackController(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\Web\\TrackController', $container));

        return $instance;
    }
}
