<?php

namespace ContainerPoRMLnn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_63dd7j7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.63dd7j7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.63dd7j7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\ArtistRepository', 'getArtistRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\ArtistRepository',
        ]);
    }
}
