<?php

namespace ContainerPoRMLnn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\TrackType' shared autowired service.
     *
     * @return \App\Form\TrackType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/TrackType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/FormListenerFactory.php';

        return $container->privates['App\\Form\\TrackType'] = new \App\Form\TrackType(($container->privates['App\\Form\\FormListenerFactory'] ??= new \App\Form\FormListenerFactory()));
    }
}
