<?php

namespace ContainerPoRMLnn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrackAutocompleteFieldService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AutocompleteField\TrackAutocompleteField' shared autowired service.
     *
     * @return \App\Form\AutocompleteField\TrackAutocompleteField
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AutocompleteField/TrackAutocompleteField.php';

        return $container->privates['App\\Form\\AutocompleteField\\TrackAutocompleteField'] = new \App\Form\AutocompleteField\TrackAutocompleteField();
    }
}
